name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: shivammathur/setup-php@v2
        name: Setup PHP
        with:
          php-version: '8.1'
          extensions: mbstring, xml, ctype, iconv, intl, sqlite3, pdo_sqlite
          coverage: xdebug

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: :memory
        run: php artisan test 